name: mugen
dependencies:
- python=3.6
- jupyter>=1.0.0
- pip
- pip:
  - moviepy>=0.2.3.5
  - librosa>=0.5.0
  - tesserocr>=2.1.3
  - Pillow>=3.4.2
  - numpy>=1.12.0
  - pysrt>=1.1.1
  - tqdm>=4.10.0
  - decorator>=4.0.11
  - dill>=0.2.7.1
  - requests>=2.21.0

  # Testing
  - pytest>=3.0.7
  - pytest-cov>=2.4.0

  # Documentation
  - sphinx>=1.6.2
