name: mugen
dependencies:
- python=2.7.12
- cython=0.25.2
- pip
- pip:
  - ipython==5.1.0
  - numpy==1.11.2
  - matplotlib==1.5.3
  - pyyaml==3.12
  - argparse==1.4.0
  - tqdm==4.10.0
  - pysrt==1.1.1
  - Pillow==3.4.2
  - tesserocr==2.1.3