name: mugen
dependencies:
- python=3.6
- pip
- pip:
  - cython>=0.25.2
  - moviepy>=0.2.3.2
  - librosa>=0.5.0
  - Pillow>=3.4.2
  - numpy>=1.12.0
  - pysrt>=1.1.1
  - tqdm>=4.10.0
  - decorator>=4.0.11
