name: mugen
dependencies:
- python=3.6
- cython>=0.25.2
- pip
- pip:
  - moviepy>=0.2.3.2
  - librosa>=0.5.0
  - tesserocr>=2.1.3
  - Pillow>=3.4.2
  - numpy>=1.12.0
  - pysrt>=1.1.1
  - tqdm>=4.10.0
  - decorator>=4.0.11

  # Testing
  - pytest>=3.0.7
  - pytest-cov>=2.4.0
