name: mugen
dependencies:
- python=3.7
- pip
- pip:
  - moviepy==0.2.3.5
  - librosa==0.7.0
  - Pillow==3.4.2
  - numpy==1.12.0
  - pysrt==1.1.1
  - tqdm==4.11.2
  - decorator==4.0.11
  - dill==0.2.7.1
  - requests==2.21.0
  - imageio==2.4.1
